### PR TITLE
Add ccache support

### PR DESCRIPTION
**Pull request by davetcoleman**
Closes https://github.com/PickNikRobotics/rviz_visual_tools/issues/87

@ahoarau seems we need to do other things to enable ccache, like tweak the catkin command or... ?

### CODE REVIEW

**Comment by ahoarau** [comment]
Yup, this happens when ccache is configure as : 
`export CXX="ccache g++-5" CC="ccache gcc-5"`
Which is how most people configure it afaik

**Comment by davetcoleman** [comment]
I'll assume you approve this, merging

**Comment by VictorLamoine** [comment]
For your information this is how `ccache` is supposed to be configured: https://askubuntu.com/questions/470545/how-do-i-set-up-ccache?answertab=active#tab-top

**Comment by ahoarau** [comment]
Thanks ! I remember reading somewhere than " masquerading " (symlinks) were not recommended. I'll try this though. I have the feeling that it will be seen by cmake as g++, which is much better than ```/usr/bin/ccache g++```

**Pull request merged**
