### PR TITLE
Remove default arguments to make function calls not ambiguous

### LINKED ISSUE #73: 3 ambiguous methods
The 3 publishPath methods, starting at:
https://github.com/PickNikRobotics/rviz_visual_tools/blob/kinetic-devel/include/rviz_visual_tools/rviz_visual_tools.h#L662
have only one mandatory parameter, just like the ones before.
```
publishPath(const std::vector<geometry_msgs::Point>& path)
publishPath(const EigenSTL::vector_Vector3d& path)
publishPath(const EigenSTL::vector_Affine3d& path)
```

So if I call any of them with only the first parameter I get an error while compiling:
> error: call of overloaded ‘publishPath(std::vector<geometry_msgs::Point_<std::allocator<void> > >&)’ is ambiguous

Could you make the optional parameters mandatory for one set of methods to resolve this ambiguity?

@v4hn

### PR DESCRIPTION
**Pull request by VictorLamoine**
Fixes #73 

Isn't there a better way to handle this problem in C++ ?! Like making one of the function preferred?

### CODE REVIEW

**Comment by mlautman** [comment]
Kinda crazy that this isn't handled better in c++. I don't think that removing just the color defaults solves it if you specify a color but not a size.. I would prefer removing all default values up to radius on those 3 values

**Comment by VictorLamoine** [comment]
I have removed the color and scale default for these functions.

**Comment by davetcoleman** [comment]
It bothered me these functions have been existing for so long in this error state, so I made some unit tests to protect them in the future

**Comment by VictorLamoine** [comment]
I think we are good guys

**Comment by davetcoleman** [comment]
@mlautman i need another review

**Pull request merged**
