### PR TITLE
Fix Eigen::Affine3d for Melodic (using Eigen::Isometry3d)

### PR DESCRIPTION
**Pull request by davetcoleman**
See https://github.com/ros-planning/moveit/pull/1096

Must be merged at the same time as moveit's

@rhaschke

### CODE REVIEW

**Comment by rhaschke** [comment]
@davetcoleman Can you merge (and release) this please as a pre-requisite of https://github.com/ros-planning/moveit/pull/1096? This should not harm downstream packages as a conversion from Isometry to Affine is always possible.

**Comment by davetcoleman** [comment]
Done, but I doubt they'll let this in for this sync: https://github.com/ros/rosdistro/pull/19532

**Comment by rhaschke** [comment]
Thanks. It's not necessary to have this released or synced right now. But this is a prerequisite for the remaining PRs.

**Comment by davetcoleman** [comment]
This is now breaking moveit_visual_tools on the build farm:
http://build.ros.org/job/Mbin_ds_dS64__moveit_visual_tools__debian_stretch_amd64__binary/20/

**Comment by rhaschke** [comment]
Yes, of course. Before I will continue with the release process, I'm waiting for feedback on https://github.com/ros-planning/moveit/issues/1225#issuecomment-441728480.

**Pull request merged**
