### PR TITLE
fix qt5_use_modules missing error

### PR DESCRIPTION
**Pull request by machinekoder**
fix for https://github.com/PickNikRobotics/rviz_visual_tools/issues/79

### CODE REVIEW

**Comment by simonschmeisser** [comment]
this is deprecated, use

   target_link_libraries( ... Qt5::Widgets ... ) 

instead. See http://doc.qt.io/qt-5/cmake-manual.html

**Comment by davetcoleman** [comment]
ping

**Comment by machinekoder** [comment]
@simonschmeisser  Then `imarker_simple_demo` is missing the `target_link_libraries`.

**Comment by davetcoleman** [comment]
This CMake kungfu is beyond me, not sure who is correct...

**Comment by davetcoleman** [comment]
Closing this, feel free to re-open if needed.

**Pull request closed without merging**
